/**
 * Compact replay-fixture loader.
 *
 * This module deliberately knows nothing about HAR files.  The normal test
 * path consumes the small, sanitized projections generated by
 * tools/extract-fixtures.js.  Raw HAR replay remains a separate diagnostic
 * path in tools/har-replay.js.
 */
import fs from 'node:fs';
import path from 'node:path';

export const COMPACT_FIXTURE_VERSION = 1;

/**
 * @param {string} filePath
 * @returns {any}
 */
export function readCompactFixture(filePath) {
  const fixture = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!fixture || typeof fixture !== 'object' || Array.isArray(fixture)) {
    throw new Error(`Compact fixture must be an object: ${filePath}`);
  }
  if (fixture.fixtureVersion !== COMPACT_FIXTURE_VERSION) {
    throw new Error(`Unsupported compact fixture version in ${filePath}: ${fixture.fixtureVersion}`);
  }
  if (fixture.sanitized !== true) {
    throw new Error(`Compact fixture is not marked sanitized: ${filePath}`);
  }
  return fixture;
}

/**
 * @param {string} rootDir
 * @returns {string[]}
 */
export function discoverCompactFixtures(rootDir) {
  const fixtureRoot = path.join(rootDir, 'tests', 'fixtures', 'extracted');
  if (!fs.existsSync(fixtureRoot)) return [];

  /** @type {string[]} */
  const files = [];
  const walk = (dir) => {
    for (const name of fs.readdirSync(dir)) {
      const full = path.join(dir, name);
      if (fs.statSync(full).isDirectory()) walk(full);
      else if (name.toLowerCase().endsWith('.json') && name !== 'manifest.json') files.push(full);
    }
  };
  walk(fixtureRoot);
  return files.sort();
}

/**
 * @param {string} rootDir
 * @param {string} platform
 * @returns {string[]}
 */
export function discoverPlatformFixtures(rootDir, platform) {
  const prefix = `${path.join(rootDir, 'tests', 'fixtures', 'extracted', platform)}${path.sep}`;
  return discoverCompactFixtures(rootDir).filter((file) => file.startsWith(prefix));
}

/**
 * @param {string} rootDir
 * @param {string} platform
 * @returns {any[]}
 */
export function loadPlatformFixtures(rootDir, platform) {
  return discoverPlatformFixtures(rootDir, platform).map((filePath) => readCompactFixture(filePath));
}
